include: package:fleasy/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.config.dart"

dart_code_metrics:
  exclude:
    - "**/*.config.dart"
#   errors:
#     invalid_annotation_target: ignore
  
#   language:
#     strict-raw-types: false

# linter:
#   rules:
#     sort_pub_dependencies: false
#     prefer_interpolation_to_compose_strings: true
#     prefer_relative_imports: true
#     avoid_dynamic_calls: true
#     avoid_multiple_declarations_per_line: false
#     prefer_single_quotes: true
#     always_use_package_imports: false
#     sort_child_properties_last: true
#     require_trailing_commas: true
#     public_member_api_docs: false
#     lines_longer_than_80_chars: false
#     implicit-dynamic: false 
#     strict-raw-types: false
#     body_might_complete_normally: false
#     type_annotate_public_apis: false