name: itorrentsearch
description: A new Flutter project.

version: 5.0.0+308

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  android_intent: ^2.0.2
  cached_network_image: ^3.1.0
  coast: ^2.0.2
  dartx: ^1.0.0
  dio: any
  firebase_messaging: ^10.0.8
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_rating_stars: ^1.0.3+4
  flutter_shimmer: ^2.1.2
  flutter_staggered_animations: ^1.0.0
  flutter_typeahead: ^3.2.1
  get_it: ^7.2.0
  freezed_annotation: null
  go_router: ^2.1.1
  hooks_riverpod: ^1.0.3
  in_app_purchase: ^1.0.9
  intl: null
  lazy_loading_list: ^1.0.0+1
  logger: any
  one_context: ^1.1.1
  package_info: ^2.0.2
  page_transition: ^2.0.4
  readmore: ^2.1.0
  retrofit: any
  shared_preferences: ^2.0.8
  simple_animations: ^4.0.1
  theme_provider: ^0.5.0
  url_launcher: ^6.0.5

dev_dependencies:
  build_runner: null
  flutter_gen: ^4.1.3
  flutter_gen_runner: null
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  freezed: null
  json_serializable: null
  retrofit_generator: any
  lint: ^1.8.2
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_gen:
  line_length: 120

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/icon/search.png
    - assets/icon/settings.png

  fonts:
    - family: "Poppins"
      fonts:
        - asset: "assets/fonts/Poppins-Black.ttf"
          weight: 900
        - asset: "assets/fonts/Poppins-Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Poppins-ExtraBold.ttf"
          weight: 800
        - asset: "assets/fonts/Poppins-Light.ttf"
          weight: 300
        - asset: "assets/fonts/Poppins-Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Poppins-Regular.ttf"
          weight: 400
        - asset: "assets/fonts/Poppins-SemiBold.ttf"
          weight: 600
        - asset: "assets/fonts/Poppins-Thin.ttf"
          weight: 100
