class Constants {
  Constants._internal();
  factory Constants() => _instance;
  static final Constants _instance = Constants._internal();

  static const String appTitle = 'iTorrent Search';
  static const bool noAds = false;
  static const String chatUrl = 'https://t.me/itorrentsupportchat';
  static const String psUrl = 'https://play.google.com/store/apps/details?id=com.icodelife.itorrentsearch';
  static const String apiUrl = '';
  static const String itapiUrl = '';
  static const String auth = '';

  static const clients = <String>[
    'com.utorrent.client',
    'hu.tagsoft.ttorrent.lite',
    'com.bittorrent.client',
    'com.delphicoder.flud',
    'com.mobilityflow.torrent',
    'com.oidapps.bittorrents',
    'com.akingi.torrent',
    'com.bittorrent.client.pro',
    'megabyte.dm',
    'com.bittorrent.android.btremote',
    'com.DroiDownloader',
    'com.brute.torrentolite',
    'com.mobilityflow.torrent',
    'com.Bittorrents_Downloader_2TS',
    'com.vuze.torrent.downloader',
    'com.Fast_Torrent_Downloader_2TS',
    'com.utorrent.web',
    'com.neogb.rtac',
    'com.delphicoder.flud.paid',
    'com.davidhodges.torrentremote',
    'com.lgallardo.qbittorrentclient',
    'com.utorrent.client.pro',
    'com.pixeltech.ptorrent',
    'bitking.torrent.downloader',
    'com.teeonsoft.ztorrent',
    'nova.torrent.downloader',
    'com.epic.app.iTorrent',
    'com.mobilityflow.torrent.prof',
    'com.boxopus.app',
    'com.nopus.smarttorrent',
    'com.frostwire.android',
    'megabyte.tdm',
    'com.teeonsoft.ztorrentpro',
    'hu.tagsoft.ttorrent.pro',
    'com.gabordemko.torrnado',
    'hu.tagsoft.ttorrent.noads',
    'com.AndroidA.DroiDownloader',
    'org.itsasoftware.torrent.streaming',
    'hu.bute.daai.amorg.drtorrent',
    'vdd.tordw',
    'com.mobilityflow.tvp',
    'com.napolovd.piratecat',
    'tv.bitx.media',
    'net.yupol.transmissionremote.app',
    'com.lgallardo.qbittorrentclientpro',
    'rocks.turkeytorrent.player',
    'org.proninyaroslav.libretorrent',
    'torrentz.downloader.getz',
    'org.itsasoftware.dast',
    'com.futorrent.torrent.client',
    'org.transdroid.lite',
    'com.vuze.android.remote',
    'vdd.panjaapps',
    'com.torrent_player',
    'com.siberianwildapps.tapeer',
    'com.gamemalt.torrentwiz',
    'com.gamemalt.torrentwiz.pro',
    'com.mediaget.android',
    'org.transdroid.full',
    'com.futorrent.torrent.client.pro',
    'com.jplatform.android.tf',
    'in.appsmash.flashtorrent',
    'org.epic.rrent',
    'com.gamemalt.streamtorrentvideos.pro',
    'com.gamemalt.streamtorrentvideos',
    'org.acestream.media',
    'intelligems.torrdroid',
    'com.jplatform.android.tf',
    'org.epic.rrent',
    'com.mwayss.torrent',
    'com.gritapps.gtorrent',
    'com.p2pgeartech.torrentgear',
    'org.viento.probreeze',
    'org.viento.breeze',
    'com.biglybt.android.client',
    'com.stevenschoen.putionew',
    'com.apptricker.mytorrent',
    'com.xender.xtorrent',
    'co.we.torrent',
    'com.realdebrid.realdebrid',
    'co.turbotorrentapp.downloader',
    'com.pk.torrentdw',
    'com.insolence.admclient',
    'com.movie.downloader.torrent.search.engine',
    'com.torrentdownler.fastandroid',
    'org.bas.torrent',
    'org.btorrent.hgcor',
    'yeolee.co.kr.ytorrent',
    'com.neptunetech.torrentdownloader',
    'torrent.movie.downloder',
    'com.techp.mediadownloader',
    'com.masterwok.bitcast',
    'com.squareup.moviedownloader',
    'app.pirate.torrent.downloader.search.engine',
    'idm.internet.download.manager',
    'idm.internet.download.manager.adm.lite',
    'idm.internet.download.manager.plus',
    'com.synology.DSdownload',
    'me.tittojose.mutorrent',
  ];
}
